// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://heqmrbbgmheflejsmccl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlcW1yYmJnbWhlZmxlanNtY2NsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2MTE4NTgsImV4cCI6MjA1MDE4Nzg1OH0.qs6vDEegWnQ9KLxUOjFg2ln7Do5NobnUoBdiXx9rb2Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);